<p><?= validation_errors() ?></p>
<?= form_open('admin/socios/modificar') ?>
  <?= form_hidden('id', $socio->id) ?><br/>
  <?= form_label('Usuario:', 'usuario') ?>
  <?= form_input('usuario', $socio->usuario) ?><br/>
  <?= form_label('Contraseña:', 'password') ?>
  <?= form_password('password', '') ?><br/>
  <?= form_label('Confirmar contraseña:', 'password_confirm') ?>
  <?= form_password('password_confirm', '') ?><br/>
  <?= form_label('Email:', 'email') ?>
  <?= form_input('email', $socio->email) ?><br/>
  <?= form_label('Nombre:', 'nombre') ?>
  <?= form_input('nombre', $socio->nombre) ?><br/>
  <?= form_label('Teléfono:', 'telefono') ?>
  <?= form_input('telefono', $socio->telefono) ?><br/>
  <?= form_submit('modificarprimera', 'Modificar socio') ?>
  <?= form_submit(array('name' => 'cancelar',
                        'value' => 'Cancelar',
                        'formaction' => 'http://localhost/web/videoclub/index.php/admin/socios/index')) ?>
<?= form_close() ?>
